# Generated by Django 5.2.4 on 2025-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='new', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
