# Generated by Django 5.2.4 on 2025-07-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250710_1715'),
    ]

    
    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_myuser DROP COLUMN IF EXISTS confirm_password;",
            reverse_sql="ALTER TABLE accounts_myuser ADD COLUMN confirm_password VARCHAR(128);"
        ),
    ]