# Generated by Django 5.2.4 on 2025-07-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_confirm_password'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_myuser DROP COLUMN IF EXISTS title;",
            reverse_sql="ALTER TABLE accounts_myuser ADD COLUMN title VARCHAR(128);"
        ),
    ]
