# Generated by Django 5.2.4 on 2025-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_created_at_alter_myuser_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
