# Generated by Django 5.2.4 on 2025-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='client_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authinfo',
            name='client_secret',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authinfo',
            name='scopes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authinfo',
            name='token_uri',
            field=models.TextField(default='https://oauth2.googleapis.com/token'),
        ),
    ]
