# Generated by Django 5.2.4 on 2025-07-25 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_authinfo_client_id_authinfo_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
