# Generated by Django 5.2.4 on 2025-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_price', models.FloatField()),
                ('unit_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_sold', models.IntegerField()),
                ('total_revenue', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_profit', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
