# Generated by Django 5.2.4 on 2025-07-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_country_order_item_type'),
        ('sale', '0002_alter_sale_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
