# Generated by Django 5.2.4 on 2025-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('order_priority', models.CharField(choices=[('H', 'H'), ('L', 'L'), ('M', 'M'), ('C', 'C')], max_length=4)),
                ('sales_channel', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
            ],
        ),
    ]
