# Generated by Django 5.2.4 on 2025-07-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.itemtype'),
        ),
    ]
