# Generated by Django 5.2.4 on 2025-07-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(default=4461650, primary_key=True, serialize=False),
        ),
    ]
