# Generated by Django 5.2.4 on 2025-07-17 07:21

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(default=order.models.generate_unique_order_id, primary_key=True, serialize=False),
        ),
    ]
