# Generated by Django 5.2.4 on 2025-07-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_id'),
        ('order', '0006_fix_userid_to_integer'),
    ]

    operations = [
    ]
