# Generated by Django 5.2.4 on 2025-07-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_20250717_1508'),
        ('order', '0008_remove_order_user'),
    ]

    operations = [
    ]
